management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSED_ENDPOINTS:health,info,metrics,prometheus}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      environment: ${SPRING_PROFILES_ACTIVE:docker}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,250ms,500ms,1s,2s,5s
  prometheus:
    metrics:
      export:
        enabled: true

