spring.application.name=RestaurantListing   
#POSTGRES_USERNAME=root
#POSTGRES_PASSWORD=Cl0udN@t1v3
#POSTGRES_DATABASE=restaurantdb
#POSTGRES_URL = jakarta.persistence.jdbc.url

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurantdb
spring.datasource.username=root
spring.datasource.password=Cl0udN@t1v3
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect